dist: CHANGES README LICENSE config ngx_http_auth_pubcookie_module.c
	tar czvf ../nginx-module-pubcookie.tar.gz  \
		 ../nginx-module-pubcookie/CHANGES \
		 ../nginx-module-pubcookie/README \
		 ../nginx-module-pubcookie/LICENSE \
 		 ../nginx-module-pubcookie/config \
 		 ../nginx-module-pubcookie/ngx_http_auth_pubcookie_module.c

