# ========================================================================
# Copyright 2008 University of Washington
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

#  $Id: Makefile.tmpl,v 1.15 2008-05-16 22:09:10 willey Exp $

OBJS=mod_pubcookie.o libpubcookie.o base64.o pbc_myconfig.o

libpubcookie.a:	$(OBJS)

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) -DAPACHE1_3 $(SSL_CFLAGS) -I$(SSL_INCDIR)/openssl -I$(SSL_INCDIR) $<

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
# DO NOT DELETE THIS LINE -- make depend depends on it.
libpubcookie.o: libpubcookie.c libpubcookie.h pbc_myconfig.c pbc_myconfig.h pubcookie.h pbc_config.h pbc_version.h

# vim: set noet:
